language: node_js
node_js:
- '6'
before_install: ./fetch.sh
env:
- KAFKA_PLEASE_LOG=verbose
deploy:
  provider: npm
  email: eiriksletteberg@gmail.com
  api_key:
    secure: PbVlyNC4sSAuS802QzGEW3TqQGOSiaAA2iNPxLmqN3zlQyOyE7Axyanyz2HieXepe0AXG7S4S7Y/bL9+YTsDouKfyf5cko5ENlIu1aA9ZnKQ3TGn44VYRGKj54jA/UzJlYznex1+WabNWlGzOjHM//ExrulntG0SdbIZuUTSXn/1HXO7yvLrgQ1VYbFpzGRnr7Jv0rcYnjj2kRVh5JIYkaRYQGOkWNyNJuSZwN8zXKE5qNtAWMyxrbmVdifoXyWczeR48BGtdODPZqRdO/s54+c6kXyx9yFiGyMNjhwj35D3YAGwATzy1CtkFYWsK1eEoIwqQZXKK673a/GbxwjgqWuc/fEp6gjesiltevTxfhS5wr2C1ZJ/xGKWMw89RpuZHNUTRPCzUUErbUDul7ypv9JOWjPLBOeglqTIxjXRxHU9RavC+pDfVDsteaUFRib9A6Ag0sHUBrBR6yu2u9IHQ5R9X3cWBZal6FE40X4sq1lbORTSs9hyvHOzsVa1ZGEI8Ock91t9JtOF5My9bxTTOObyY/P4P2+/3ifq+j6Kd3YU7IgvaYruOCu4qMWe0Yg7SPIrPtkUfu8fGXx4ac/OUF6C3VUJNCj6XXqwnsOwHRvz6F1tzrel8kDdvL4AZm/zPCd4YWuLSffANAvKohjwUomTGSczZgFwXLFZqSUPzzI=
  on:
    tags: true
    repo: eirslett/kafka-please
  skip_cleanup: true
