language: node_js
node_js:
- '6'
before_install: ./fetch.sh
env:
- KAFKA_PLEASE_LOG=verbose
deploy:
  provider: npm
  email: eiriksletteberg@gmail.com
  api_key:
    secure: w3HNKrLwtSROPkrEJ68ziFz1QyBNgGkipofVinxmwgLRL4vexeWqM/UK6cXE7HL3h8EsDcKxExe+z6i5XAM4TqKPUTM/kc5/+597SjtVMZlYrv0svFIM2BtWTyl5lMiTKwBQcg12SrEnZvJdj2CrSCT5rTH4vu/w2v944F9Jh3vjOE1g+RWvZWPEEX85eVXgLEKNbq9pPBUfMFImmFi3JsLp+elYc6U81GCOMHMFaC+lDbgMMJu2k5I+w5vCyfdyLMKqOr3Z1/+ygEpQ9/jIErBqCLS+HezFnP3GcOlxzG2NPU3d+MsabRuXxCSrVXiGj0oCbVGgravh0XqUg9K+csMmJkTBCJCPYLFXq9TWYZgH9307DmSOVPZJ6k8X4WrBXiMHWGxEXONcU4l0aChJCJuuFNvHcq4t+0hvYBgNsZ3Xl3qSEb00vJ5YXv0BI02+nb6ryS/sH1z17STwhlqefNzXyaI+Wyj1HUivAQr7Xbp6iJgowHbbZTUkcqhsib+m02rWGMlPxJ0UBZ9lhn9imjsV2+2Go6DeeFtVLqkEHAfDXlNSZ2BTVlziHIz+T6DZTxxGq2J6+omWHJ4Grt40d5V4Ub3YnrYLndUEvVyAwSfPAF6Qe8kBrYVGfeIxSdGN1WiQyQtkHSicqH95ZTBCebwTdqrHAToJT93v/e1eUEE=
  on:
    tags: true
    repo: eirslett/kafka-please
  skip_cleanup: true
